### ISSUE TITLE
Crash logs

I'm running GrapheneOS

### ISSUE THREAD

**Issue by tashijayla** [Leonidius20/RecordingStudio#15]
*

**Comment by Leonidius20** [comment]
Hello and thank you for reporting the issue.
Could you tell which audio settings you are using (container format, codec, mono/stereo, sample rate)? Does changing the sample rate help? If not, does clearing the app's data help?

**Comment by Leonidius20** [comment]
i figured it out.
version 0.1.5 should fix it. it's already available in the releases section.

**Comment by tashijayla** [comment]
Yes, the new version works perfectly. Thank you ❤️‍🔥🎉
