### ISSUE TITLE
Re-sampling between different kHz / Choosing the sample rate at recording

### ISSUE THREAD

**Issue by RustoMCSpit** [Leonidius20/RecordingStudio#24]
### Feature description

There are different kHz amounts: 44.1 kHz, 48kHz etc.
Allowing a user to choose the sample rate and resample audio is thus needed.

### Why do you want this feature?

Some programs take different amounts, different file sizes, etc.

### Additional information

https://github.com/FossifyOrg/Voice-Recorder/issues/32 related to this

https://github.com/FossifyOrg/Voice-Recorder/issues/33

**Comment by Leonidius20** [comment]
you can already change sample rate in the latest version of this app

**Comment by RustoMCSpit** [comment]
> you can already change sample rate in the latest version of this app
