### ISSUE TITLE
recording audio on behalf of other app with intent filter & activity result not working as intended

### ISSUE THREAD

**Issue by pvagner** [Leonidius20/RecordingStudio#4]
Hello,
This feature is recording audio into designated folder. The target app the recording has been started from may not have storage permissions or scope to read that file. I think we need to implement a data provider for this.
See [how axet audio recorder does it for an idea](https://gitlab.com/axet/android-audio-recorder/-/commit/1b2f5a5eb2c7894b382f3102af30c92580e710be).
Also if I may add a simple feature request to this, it would be nice to start recording directly when the app is inwoked by this intent without having to press the record button. I like to use this feature with the FairEmail app. It has a Record sound button on the bottom bar when composing email.

**Comment by Leonidius20** [comment]
As for starting the recording right away without pressing the button, that would deprive the user of the ability to adjust audio settings before starting the recording. Are there any additional benefits to starting recording right away apart from not having to press 2 buttons?

**Comment by pvagner** [comment]
Ah yes, you are right, that's a good point.
I assumed audio settings are not used all the time i.e. I have set it once and forgot about it. Feel free to ignore this part then and only concentrate of the functionality of this feature.

**Comment by Leonidius20** [comment]
Should be fixed in version 0.1.2, available now in the Releases section.
